# frozen_string_literal: true

require "pipedrive/resources/activity"
require "pipedrive/resources/activity_type"
require "pipedrive/resources/call_log"
require "pipedrive/resources/currency"
require "pipedrive/resources/deal"
require "pipedrive/resources/file"
require "pipedrive/resources/filter"
require "pipedrive/resources/global_message"
require "pipedrive/resources/goal"
require "pipedrive/resources/lead_label"
require "pipedrive/resources/lead_source"
require "pipedrive/resources/lead"
require "pipedrive/resources/organization"
require "pipedrive/resources/pipeline"
require "pipedrive/resources/product"
require "pipedrive/resources/person"
require "pipedrive/resources/note"
require "pipedrive/resources/stage"
require "pipedrive/resources/team"
require "pipedrive/resources/user"
require "pipedrive/resources/subscription"
require "pipedrive/resources/webhook"
